### ISSUE TITLE
Problem about "bandwidth calculation"

### ISSUE THREAD

**Issue by KW-Ho** [jaak-s/rDEA#14]
I am new to R and this "rDEA" package and would like to ask how to solve the following problem: 
`Error in bw.ucv(delta_hat_2m) : non-finite x[11] in bandwidth calculation`

I just followed the example code to do DEA but the error message pop out. 
Please help me to solve the problem, thank you!!

**Comment by jaak-s** [comment]
Thank you for the bug report. Would it be possible to provide an example code and data that causes the error? The smallest example data causing the error is preferred.

**Comment by KW-Ho** [comment]
Hello, 

 

Please find the attachment and the code below. 

 

The code I used showed as follows:

 

Y = X2007_2012July_Panel_Data[c('AMRRes', 'AMIRes','NetMeteringRes','EnergyEffAnnRes','LMActualPeakRedAnnRes','NumberofCustomersRes')]

X = X2007_2012July_Panel_Data[c('DirectCostEEF', 'IncentiveEEF', 'DirectCostLM','IncentiveLM','IndirectCost')]

 

di_robust = dea.robust(X, Y, model='intput', RTS="variable", B=1000, alpha=0.05, bw="bw.ucv", bw_mult=1)

di_robust$theta_hat_hat

 

And the error message will be: 

Error in bw.ucv(delta_hat_2m) : non-finite x[4] in bandwidth calculation

 

By the way, if I change model to output, there generates the outcome but some of the value is negative which is not between 0 to 1. 

 

Many thanks!

 

Best regards, 

 

Best regards,

——————————————

KW, HO

 

mail: r04741052@g.ntu.edu.tw <mailto:r04741052@g.ntu.edu.tw>

**Comment by jaak-s** [comment]
Unfortunately it seems the attachment is not possible in github.
Can you send the to my e-mail: jaak.simm@gmail.com
Thanks.

**Comment by jaak-s** [comment]
I found that if you remove the rows and columns that have all zeros, dea.robust works. But your setup is too large, too many input and output features causes a drastic slowdown.

Here is the code for removing the empty lines and I use smaller number of X and Y columns:
```R
x = read.csv("test1.csv")
X = x[c('DirectCostEEF', 'IncentiveEEF')]
Y = x[c('AMRRes', 'AMIRes')]
idx = (rowSums(Y) != 0) & (rowSums(X) != 0)
Xnz = X[idx,]
Ynz = Y[idx,]
Xnz
Ynz
di_robust = dea.robust(Xnz, Ynz, model='input', RTS="variable", B=1000, alpha=0.05, bw="bw.ucv", bw_mult=1)
```
I'll close the bug for now. I'll plan to add an error if there is an input or output row with all zeros in the dataset.

**Comment by KW-Ho** [comment]
Hello, 

 

Thank you so much! 

 

Best regards,

——————————————

KW, HO

 

mail: r04741052@g.ntu.edu.tw <mailto:r04741052@g.ntu.edu.tw> 

——————————————
