### ISSUE TITLE
Package removed from CRAN

### ISSUE THREAD

**Issue by omit01** [jaak-s/rDEA#18]
Dear developer,

I had to use your package today, but saw it was removed from the CRAN of the R website (https://cran.r-project.org/web/packages/rDEA/index.html).
Especially the removal of the documentation is a strugle for me.

Could it be possible to update the package and upload it again?

Best regards,
Timo

**Comment by jaak-s** [comment]
Dear Timo,

Now fixed. Should be in CRAN next week.

Best,
Jaak
