### ISSUE TITLE
Negative theta?

### ISSUE THREAD

**Issue by gitcanzo** [jaak-s/rDEA#20]
I am trying to perform an input-oriented DEA. From my understanding, the resulting efficiency coefficient theta should be in the [0, 1] range by construction(?). However, some of the coefficients I obtain are negative and/or with confidence intervals outside the range. Am i doing something wrong, or is this an issue with the rDEA package?

Here is my code, including the exact data I am using (all variables have been divided by their cross-section mean to bring them to common scale):

`
## Import libraries
library(data.table)
library(fastpipe)
library(rDEA)

inputs <- structure(list(exp = c(1.45631953364524, 1.66436627311178, 
                                 0.49196775193678, 2.3921923224414, 0.566080570390277, 1.52765097750528, 
                                 1.27803808944191, 1.04608131903838, 0.503721239512992, 0.36355050866804, 
                                 1.54003174549243, 0.954059544697017, 0.446706427106333, 0.366260202876539, 
                                 3.14166782031816, 1.57819541789705, 0.359730199930916, 0.685481093042031, 
                                 0.344358655709796, 2.33037483179135)), row.names = c(NA, -20L
                                 ), class = c("data.table", "data.frame"))

outputs <- structure(list(re = structure(c(0.987838685512543, 1.00511574745178, 
                                       0.999720394611359, 1.02197182178497, 1.06660687923431, 1.06061482429504, 
                                       1.00458967685699, 1.01615834236145, 0.932821154594421, 0.970696270465851, 
                                       1.05653548240662, 0.971303999423981, 0.976226985454559, 0.970465421676636, 
                                       0.95845764875412, 0.988636434078217, 1.04384517669678, 1.00294649600983, 
                                       0.933982729911804, 1.03146553039551)), 
               mat = structure(c(1.00566446781158, 1.02406275272369, 
                                    1.00672328472137, 1.02673959732056, 1.05499053001404, 1.02251279354095, 
                                    0.998539805412292, 1.00788450241089, 0.909778714179993, 0.969666600227356, 
                                    1.00705635547638, 0.980766892433167, 0.999988555908203, 0.969885349273682, 
                                    0.974380731582642, 1.04655814170837, 1.03933596611023, 0.992653965950012, 
                                    0.979910254478455, 1.01260888576508)), 
               sci = structure(c(0.996497690677643, 1.01479399204254, 
                                       1.01076185703278, 1.00230967998505, 1.07854735851288, 1.06181609630585, 
                                       1.00300145149231, 1.0233713388443, 0.918883144855499, 0.978453516960144, 
                                       1.00938296318054, 0.952207505702972, 0.991350531578064, 0.980804085731506, 
                                       0.970025718212128, 1.02417480945587, 1.03974294662476, 1.0003570318222, 
                                       0.94414210319519, 1.01616036891937))),
               row.names = c(NA, -20L), class = c("data.table", "data.frame")) 

dmus <- 1:20

model <- dea.robust(X=inputs, Y=outputs, model="input", RTS="variable",
                    B=1000, alpha=0.05)

# Merge results
results <- data.table(dmus,
                      model[["theta_hat_hat"]],
                      model[["theta_ci_low"]],
                      model[["theta_ci_high"]]) %>%
  setorder(., -V2)
colnames(results)[2] <- "theta_hat"
colnames(results)[3] <- "ci_low"
colnames(results)[4] <- "ci_high"
`

**Comment by jaak-s** [comment]
There is no issue with the data and no issue with the rDEA package.

Negative `theta_hat_hat` can naturally happen with Simar and Wilson's 1998 method. However, there is an alternative bias correction scheme where instead of subtracting the bias (as in SW1998), it is removed by dividing. In that case `theta_hat_hat` is guaranteed to be positive. We will implement this approach in the future.

At the moment you can still interpret the scores as they are, i.e., the firms with negative scores have poor efficiency.

**Comment by gitcanzo** [comment]
Thanks! Does this also explain confidence intervals being out of boundaries (both below 0 and above 1)?

**Comment by jaak-s** [comment]
Yes, the confidence intervals are also due to SW1998 applying linear correction to the efficiency scores.

**Comment by gitcanzo** [comment]
By the way, should the description in [here](https://search.r-project.org/CRAN/refmans/rDEA/html/dea_robust.html) not be corrected then? 
![image](https://github.com/jaak-s/rDEA/assets/34713795/869b9bd4-5985-47c7-9944-7c3da06f26f9)
